/*
    username: Nobinberg
    password: amm_2017
*/

create table utenti(
    id integer generated by default as identity primary key,
    nome varchar(50),
    cognome varchar(50),
    email varchar(50),
    password varchar(20),
    urlfoto varchar(100)
)

create table post(
    id integer generated by default as identity primary key,
    contenuto varchar(500),
    autore varchar(50),
    allegato varchar(100)
)

create table gruppi(
    id integer generated by default as identity primary key,
    nome varchar(50),
    descrizione varchar(500),
    numeromembri int,
    admin varchar(50)
)